baseURL = "https://justinfear.com"
languageCode = "en-us"
title = "Justin Fear"

theme = "toha"
enableEmoji = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[params]
gitRepo = "https://github.com/jfear/justinfear.com"
gitBranch = "main"
enableBlogPost = true
enableTOC = true

[params.newsletter]
enable = false

[logo]
main = "images/profile.png"
favicon = "images/profile.png"